name: rani-ukamble-group/reusable_files_application
true:
  push: null
  workflow_dispatch: null
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    uses: Target-orgn/target-simple-reusable1/.github/workflows/build.yml@demo1
  test:
    uses: Target-orgn/target-simple-reusable1/.github/workflows/test_file.yml@demo1
