name: Use Multiple Shared Workflows
'on':
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        required: true
        default: production
concurrency:
    group: "${{ github.ref }}"
    cancel-in-progress: true

jobs:
  call-build:
    uses: Target-orgn/target-simple-reusable1/.github/workflows/build.yml@demo1
    with:
      environment: ${{ inputs.environment }}
  call-test:
    uses: Target-orgn/target-simple-reusable1/.github/workflows/test_file.yml@demo1
    with:
      environment: ${{ inputs.environment }}
