name: Use Shared Workflow
'on':
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        required: true
        default: production
jobs:
  call-shared:
    uses: Target-orgn/target-simple-reusable1/.github/workflows/build.yml@demo1
    with:
      environment: ${{ inputs.environment }}
